### ISSUE TITLE
16.04 # Create permanent settings directory OSError: [Errno 13] Permission denied: 'fern-settings'

### ISSUE THREAD

**Issue by alphaaurigae** [savio-code/fern-wifi-cracker#114]
```
06:03 $ fern-wifi-cracker 
Traceback (most recent call last):
  File "/usr/local/bin/fern-wifi-cracker", line 70, in <module>
    initialize()
  File "/usr/local/bin/fern-wifi-cracker", line 20, in initialize
    create_directory()
  File "/usr/local/bin/fern-wifi-cracker", line 56, in create_directory
    os.mkdir('fern-settings')                               # Create permanent settings directory
OSError: [Errno 13] Permission denied: 'fern-settings'

```

above ERR on xubuntu 16.04 

pre 
`GITREPOROOT=/opt/ITSEC/6.Wireless/1.Wifi/fern-wifi-cracker/savio-code/fern-wifi-cracker/Fern-Wifi-Cracker
EXECUTEABLE1=execute.py
EXECUTEABLE2=fern-wifi-cracker
#
cd $GITREPOROOT
sudo rm -f /usr/local/bin/$EXECUTEABLE2
git clean -f 
git fetch origin
git reset --hard origin/master
git pull
echo "#!/bin/bash
cd /opt/ITSEC/6.Wireless/1.Wifi/fern-wifi-cracker/savio-code/fern-wifi-cracker/Fern-Wifi-Cracker

python execute.py" >> $EXECUTEABLE2
sudo chmod +x $EXECUTEABLE1
sudo chmod +x $EXECUTEABLE2
sudo ln -s $GITREPOROOT/$EXECUTEABLE1 /usr/local/bin/$EXECUTEABLE2`

**Comment by savio-code** [comment]
Hello, Its a permission error, Please try running execute.py as root

root@host:~# sudo python execute.py

**Comment by alphaaurigae** [comment]
https://github.com/alphaaurigae/ITSEC-Install-Scripts/commit/2ba202632939f8cfb2708161f7515866461bbcca

missed that out, thx
