### ISSUE TITLE
future is deprecated 

### ISSUE THREAD

**Issue by milad0123** [savio-code/fern-wifi-cracker#115]
hi.
installed on ubnutu 16.04
but mac geolocatory dosent work or gives me this error:
future has deprecated.

**Comment by harshal13control** [comment]
may be you need to use savio code to fix all bugs

**Comment by harshal13control** [comment]
i got it ,,,finally
that feature is deprecated [remove] from fern wifi latest version ,,you need to uninstall latest version of fern wifi from your linux and then download previous version file of fern wifi ..savio code also doesnt work on it

**Comment by d4rkcon** [comment]
Did anyone get this working?

**Comment by savio-code** [comment]
The feature was deprecated because the API from google that was needed to track geo-location is no longer free. hence even older versions of fern wont work for geotracking because they are actively blocked by google servers.

**Comment by d4rkcon** [comment]
Is it possible to pay for the Google API and get it working?

**Comment by Rodricks111** [comment]
I am having the same issue. With new update I can't use geolocation. Is there any alternatives to use it?

**Comment by pruthvi210** [comment]
please reply  i have lost my mobile 
i want to trace it please please please

**Comment by omarN1** [comment]
have anyone found a solution for this problem yet ,I need to find a way to trace my mobile or any device with MAC Address , also if anyone has another way for tracking devices I would like to Know

**Comment by omarN1** [comment]
@pruthvi210 have you found a way to find it?

**Comment by leoellis2022** [comment]
Does anyone have a newer way to trace things by the MAC address

**Comment by Mrslk251** [comment]
@Stephennjakai Didn't get it. Pls elaborate
