### ISSUE TITLE
pyQT5 **LAST  RITES** for qt4... ** 

### ISSUE THREAD

**Issue by necrose99** [savio-code/fern-wifi-cracker#126]
many distros soon will go **LAST  RITES** for qt4... 
@Gentoo & @Pentoo Linux (Pentoo depends on Gentoo)  & @Debian also... 
https://wiki.debian.org/Qt4Removal 

https://github.com/ales-erjavec/anyqt  allows for either..

**https://github.com/KDAB/Qt4to5**   for some projects "Automagical Porting"

**Comment by savio-code** [comment]
Thanks for the information, work will begin on porting to PyQt5

**Comment by savio-code** [comment]
Fern Wifi cracker has been ported to PyQt5
