### ISSUE TITLE
No wireless interface was found

### ISSUE THREAD

**Issue by Olaniyi0** [savio-code/fern-wifi-cracker#130]
Python version: 2.7.16
Aircrack version: rcrack-ng 1.5.2
Qt version: 5.11.3
OS: Parrot OS

**Comment by ssnkhan** [comment]
+1

Python version: 2.7.16
Aircrack version: rcrack-ng 1.5.2
OS: Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux

**Comment by Olaniyi0** [comment]
Seems like no one is up for help here :(

**Comment by savio-code** [comment]
Hello,

When the message that message is displayed it means you either don't have a wireless card connected to your Linux instance or your wireless card is not compatible. 

You need to get a wireless usb card that is compatible.

**Comment by falmauner** [comment]
and how oyou know is compatible
