### ISSUE TITLE
FernWifi: not able to use some wifi cards after setting it into monitor mode

### ISSUE THREAD

**Issue by RoseDeSable** [savio-code/fern-wifi-cracker#146]
Hi,
 if airmon-ng can set a card into monitor mode, fernwifi is also able to do it. But, if airmon-ng doesn't rename wlanx into wlanxmon, fernwifi writes "problem occured while setting up the monitor mode ....". Here an example for such a case:

PHY Interface Driver Chipset

phy0 wlan0 b43 Broadcom on bcma bus, information limited
                (monitor mode enabled)

The result of iwconfig is:

wlan0 IEEE 802.11 Mode:Monitor Frequency:2.457 GHz Tx-Power=20 dBm
          Retry short limit:7 RTS thr:off Fragment thr:off
          Power Management:on

airmon-ng works with wlan0 without problems.

Another problem is the setting back into the managed mode. After "airmon-ng stop" wlan0 stays in mode "monitor". I must set it with iwconfig into the managed mode.

The card has the following identification:

Network controller: Broadcom Inc. and subsidiaries BCM43228 802.11a/b/g/n

If I use my usb-wlancard "Qualcomm Atheros AR9271" airmon-ng rename the identifier into wlanxmon, and fernwifi correctly works ! Instead driver b34 the driver name for this card is ath9k_htc is used.

Bye
Rose

**Comment by RoseDeSable** [comment]
Hello,
 a further problem is, that airmon-ng stops some processes like NetworkManager in the case, where the interface name is not renamed to wlanxmon. The user isn't informed. Instead of the elder versions the actual version of the NetworkManger must run whole the time. It run the dhcp-client as a task not as a standalone process outside of itself. Therefore dhcp-managed interfaces like eth0 for wired networks cannot renew their ip addresses. As result the communication is lost after reaching the lease time for the ip address. This is a problem, if a system is managed from distance over ssh. This could also be the case, if someone uses fernwifi in a drone, that communicates over the cell phone network with him. 

Bye
Rose

**Comment by savio-code** [comment]
Thanks for the notificaton, work will begin to fix this issue
