### ISSUE TITLE
No Networks Found

### ISSUE THREAD

**Issue by mjack360** [savio-code/fern-wifi-cracker#149]
I can get my network adapter into monitor mode and start the scan but it never pulls in any networks. I have no issue pulling networks with airodump-ng though. Any idea what might be wrong?

**Comment by savio-code** [comment]
Are you using Kali Linux, what version of air crack are you using?

Sent from Yahoo Mail on Android 
 
  On Sat, 6 Mar 2021 at 1:53 am, mjack360<notifications@github.com> wrote:   


I can get my network adapter into monitor mode and start the scan but it never pulls in any networks. I have no issue pulling networks with airodump-ng though. Any idea what might be wrong?

**Comment by mjack360** [comment]
I'm on Kali version 2021.1 and here is the aircrack-ng version which states it is up to date.

(1:1.6+git20210130.91820bc-1)

**Comment by savio-code** [comment]
Issue has been fixed, please update to latest version
