### ISSUE TITLE
Why is there none detected???

### ISSUE THREAD

**Issue by chccc1994** [savio-code/fern-wifi-cracker#160]
```python
sudo python3 execute.py
```
**ERROR**:
Error occurred during scan:  no element found: line 1, column 0
wash: no process found
Error occurred during scan:  no element found: line 1, column 0

![image](https://user-images.githubusercontent.com/68001817/156294485-91576e6f-a215-490c-b1dc-6378d57ab0b3.png)

**Comment by savio-code** [comment]
Update to latest version... Issue has been fixed
