### ISSUE TITLE
Field to run the script

### ISSUE THREAD

**Issue by Jamel-miraoui** [savio-code/fern-wifi-cracker#178]
![Screenshot from 2023-09-06 15-46-25](https://github.com/savio-code/fern-wifi-cracker/assets/105128037/5ef2a395-5732-4994-9b6e-f3145a789a90)

**Comment by Jamel-miraoui** [comment]
unfortunately no

**Comment by savio-code** [comment]
Please install pyqt5 by running this in terminal:

apt install PyQt5

**Comment by Jamel-miraoui** [comment]
thx
