### ISSUE TITLE
AP's NOT DETECTING!

### ISSUE THREAD

**Issue by ktauchathuranga** [savio-code/fern-wifi-cracker#180]
**AP's not detecting, and i noticed in others when click "Scan for Access Points" first status message is "initializing" and then "active". but mine going straight to "active". and not detecting any AP's.**

![image](https://github.com/savio-code/fern-wifi-cracker/assets/79928743/bb98356e-c4bb-4481-be6e-1841546e5843)

**Comment by savio-code** [comment]
When you use command line using airodump-ng, are you able to detect the access points?

**Comment by ktauchathuranga** [comment]
yes, i can see access points and stations🖤

**Comment by savio-code** [comment]
There has been some updates to fern since the initial report of this issue. Please confirm if you still experience this problem

**Comment by ktauchathuranga** [comment]
its working now...
